"""empty message

Revision ID: 495a82c531df
Revises: 
Create Date: 2022-07-02 10:24:08.890946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495a82c531df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reportTo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reportTo', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
