"""empty message

Revision ID: a67725a1328d
Revises: 
Create Date: 2022-06-30 11:48:56.525506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67725a1328d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('internalDomain', sa.String(length=15), nullable=True),
    sa.Column('externalDomain', sa.String(length=20), nullable=True),
    sa.Column('owaAdd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EmployeeSysadmin',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], )
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('EmployeeSysadmin')
    op.drop_table('customers')
    # ### end Alembic commands ###
